# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-29 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20181029_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher_id',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
