# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-23 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_remove_userinfo_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
