# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-29 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20181029_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='addr',
            field=models.CharField(default='苦境', max_length=128),
        ),
    ]
